
package com.cjit.ws.jdkClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VatServicePortType", targetNamespace = "http://service.esb.soa.pub.ebao.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VatServicePortType {


    /**
     * 
     * @param reqXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "VatService")
    @WebResult(targetNamespace = "http://service.esb.soa.pub.ebao.com/")
    @RequestWrapper(localName = "VatService", targetNamespace = "http://service.esb.soa.pub.ebao.com/", className = "com.cjit.ws.jdkClient.VatService")
    @ResponseWrapper(localName = "VatServiceResponse", targetNamespace = "http://service.esb.soa.pub.ebao.com/", className = "com.cjit.ws.jdkClient.VatServiceResponse")
    public String vatService(
        @WebParam(name = "reqXML", targetNamespace = "http://manage.server.ws.sinosoft.com/")//{http://manage.server.ws.sinosoft.com/
        String reqXML);

}
