
package com.cjit.ws.jdkClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VatService", targetNamespace = "http://service.esb.soa.pub.ebao.com/", wsdlLocation = "http://10.3.40.10:7001/ls/services/VatService?wsdl")
public class VatService_Service
    extends Service
{

    private final static URL VATSERVICE_WSDL_LOCATION;
    private final static WebServiceException VATSERVICE_EXCEPTION;
    private final static QName VATSERVICE_QNAME = new QName("http://service.esb.soa.pub.ebao.com/", "VatService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.3.40.10:7001/ls/services/VatService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VATSERVICE_WSDL_LOCATION = url;
        VATSERVICE_EXCEPTION = e;
    }

    public VatService_Service() {
        super(__getWsdlLocation(), VATSERVICE_QNAME);
    }

    /*public VatService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VATSERVICE_QNAME, features);
    }*/

    public VatService_Service(URL wsdlLocation) {
        super(wsdlLocation, VATSERVICE_QNAME);
    }

    /*public VatService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VATSERVICE_QNAME, features);
    }*/

    public VatService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /*public VatService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }*/

    /**
     * 
     * @return
     *     returns VatServicePortType
     */
    @WebEndpoint(name = "VatServicePort")
    public VatServicePortType getVatServicePort(QName VatServicePort) {
        return super.getPort(VatServicePort, VatServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VatServicePortType
     */
    @WebEndpoint(name = "VatServicePort")
    public VatServicePortType getVatServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.esb.soa.pub.ebao.com/", "VatServicePort"), VatServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VATSERVICE_EXCEPTION!= null) {
            throw VATSERVICE_EXCEPTION;
        }
        return VATSERVICE_WSDL_LOCATION;
    }

}
