package com.sinosoft.ws.job.client.callservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "CallServiceFactory", targetNamespace = "http://manage.server.ws.sinosoft.com/")
public class CallServiceFactory extends Service {

	private static URL CALLSERVICEFACTORY_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.sinosoft.ws.job.client.callservice.CallServiceFactory.class
					.getName());

	public static void setURL(String wsdl) {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.sinosoft.ws.job.client.callservice.CallServiceFactory.class
					.getResource(".");
			url = new URL(baseUrl, wsdl);
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: '"
					+ wsdl + "', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CALLSERVICEFACTORY_WSDL_LOCATION = url;
	}

	public CallServiceFactory(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CallServiceFactory() {
		super(CALLSERVICEFACTORY_WSDL_LOCATION, new QName(
				"http://manage.server.ws.sinosoft.com/", "CallServiceFactory"));
	}

	/**
	 * 
	 * @return returns CallService
	 */
	@WebEndpoint(name = "CallServicePort")
	public CallService getCallServicePort() {
		return super.getPort(new QName("http://manage.server.ws.sinosoft.com/",
				"CallServicePort"), CallService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns CallService
	 */
	@WebEndpoint(name = "CallServicePort")
	public CallService getCallServicePort(WebServiceFeature... features) {
		return super.getPort(new QName("http://manage.server.ws.sinosoft.com/",
				"CallServicePort"), CallService.class, features);
	}

}
