
package com.sinosoft.ws.job.client.callservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CallService", targetNamespace = "http://manage.server.ws.sinosoft.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CallService {


    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "invoke", targetNamespace = "http://manage.server.ws.sinosoft.com/", className = "com.sinosoft.ws.job.client.callservice.Invoke")
    @ResponseWrapper(localName = "invokeResponse", targetNamespace = "http://manage.server.ws.sinosoft.com/", className = "com.sinosoft.ws.job.client.callservice.InvokeResponse")
    public String invoke(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

}
